// <auto-generated />
namespace Rilke_Schule_Student_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedCSSPlaceHoldersForAddTripAndAddStudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedCSSPlaceHoldersForAddTripAndAddStudent));
        
        string IMigrationMetadata.Id
        {
            get { return "201611140016475_AddedCSSPlaceHoldersForAddTripAndAddStudent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
