// <auto-generated />
namespace Rilke_Schule_Student_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RegistrationUpdatedModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegistrationUpdatedModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201611102159180_RegistrationUpdatedModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
